package gui;

import logic.*;
import fileio.*;

/**
 * Graafinen käyttöliittymä jatsi-noppapelille.
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Jatsi-pelin instanssi.
     */
    private Game jatsi;
    
    /**
     * High score -lista pelille.
     */
    private final Highscores highscores;
    
    /**
     * Taulukko kaikista noppayhdistelmistä pelissä.
     */
    private final String[] diceCombinations = {"Ones", "Twos", "Threes", "Fours", "Fives", "Sixes", "Pair", "Two Pairs", "Three of a Kind", "Four of a Kind", "Small Straight", "Large Straight", "Full House", "Chance", "Yatzy"};
    
    /**
     * Muuttuja kertoo, onko kyseinen peli pakkojatsi (true) vai perusjatsi (false).
     */
    private boolean pakkojatsi;
    
    /**
     * Apumuuttuja pakkojatsiin.
     */
    private int pakkocounter;
    
    /**
     * Konstruktori.
     */
    public GUI() {
        initComponents();
        this.highscores = new Highscores("highscores.dat");
    }
    
    /**
     * Metodi muuttaa noppayhdistelmän kokonaisluvuksi, jota käytetään taulukon indekseissä.
     * @param combination noppayhdistelmä
     * @return noppayhdistelmä kokonaislukuna
     */
    private static int combinationToInteger(String combination) {
        combination = combination.toLowerCase();
        switch (combination) {
            case "ones": return 0;
            case "twos": return 1;
            case "threes": return 2;
            case "fours": return 3;
            case "fives": return 4;
            case "sixes": return 5;
            case "upper total": return 6;
            case "bonus": return 7;
            case "pair": return 8;
            case "two pairs": return 9;
            case "three of a kind": return 10;
            case "four of a kind": return 11;
            case "small straight": return 12;
            case "large straight": return 13;
            case "full house": return 14;
            case "chance": return 15;
            case "yatzy": return 16;
            case "total": return 17;
        }
        return 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Scorecard = new javax.swing.JTable();
        rollButton = new javax.swing.JButton();
        dieButton1 = new javax.swing.JToggleButton();
        dieButton2 = new javax.swing.JToggleButton();
        dieButton3 = new javax.swing.JToggleButton();
        dieButton4 = new javax.swing.JToggleButton();
        dieButton5 = new javax.swing.JToggleButton();
        menuBar = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        newGameMenuItem = new javax.swing.JMenuItem();
        highScoresMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);

        Scorecard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Player 1", "Player 2", "Player 3", "Player 4", "Player 5", "Player 6"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Scorecard.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Scorecard);
        Scorecard.setValueAt("Ones", 0, 0);
        Scorecard.setValueAt("Twos", 1, 0);
        Scorecard.setValueAt("Threes", 2, 0);
        Scorecard.setValueAt("Fours", 3, 0);
        Scorecard.setValueAt("Fives", 4, 0);
        Scorecard.setValueAt("Sixes", 5, 0);
        Scorecard.setValueAt("Upper Total", 6, 0);
        Scorecard.setValueAt("Bonus", 7, 0);
        Scorecard.setValueAt("Pair", 8, 0);
        Scorecard.setValueAt("Two Pairs", 9, 0);
        Scorecard.setValueAt("Three of a Kind", 10, 0);
        Scorecard.setValueAt("Four of a Kind", 11, 0);
        Scorecard.setValueAt("Small Straight", 12, 0);
        Scorecard.setValueAt("Large Straight", 13, 0);
        Scorecard.setValueAt("Full House", 14, 0);
        Scorecard.setValueAt("Chance", 15, 0);
        Scorecard.setValueAt("Yatzy", 16, 0);
        Scorecard.setValueAt("TOTAL", 17, 0);

        rollButton.setText("Roll!");
        rollButton.setEnabled(false);
        rollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollButtonActionPerformed(evt);
            }
        });

        dieButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/die_1.png"))); // NOI18N
        dieButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieButton1ActionPerformed(evt);
            }
        });

        dieButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/die_1.png"))); // NOI18N
        dieButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieButton2ActionPerformed(evt);
            }
        });

        dieButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/die_1.png"))); // NOI18N
        dieButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieButton3ActionPerformed(evt);
            }
        });

        dieButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/die_1.png"))); // NOI18N
        dieButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieButton4ActionPerformed(evt);
            }
        });

        dieButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/die_1.png"))); // NOI18N
        dieButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieButton5ActionPerformed(evt);
            }
        });

        Menu.setText("File");

        newGameMenuItem.setText("New game");
        newGameMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameMenuItemActionPerformed(evt);
            }
        });
        Menu.add(newGameMenuItem);

        highScoresMenuItem.setText("High scores");
        highScoresMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScoresMenuItemActionPerformed(evt);
            }
        });
        Menu.add(highScoresMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        Menu.add(exitMenuItem);

        menuBar.add(Menu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 177, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rollButton, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dieButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dieButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dieButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dieButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dieButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dieButton1)
                    .addComponent(dieButton2)
                    .addComponent(dieButton3)
                    .addComponent(dieButton4)
                    .addComponent(dieButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rollButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void rollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollButtonActionPerformed
        jatsi.rollDice();
        jatsi.turn++;
        dieButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/die_" + jatsi.dice[0].getValue() + ".png")));
        dieButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/die_" + jatsi.dice[1].getValue() + ".png")));
        dieButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/die_" + jatsi.dice[2].getValue() + ".png")));
        dieButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/die_" + jatsi.dice[3].getValue() + ".png")));
        dieButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/die_" + jatsi.dice[4].getValue() + ".png")));
        if (jatsi.turn == 3) {
            jatsi.turn = 0;
            rollButton.setEnabled(false);
            if (!pakkojatsi) {
                java.util.ArrayList<String> list = new java.util.ArrayList<>();
                for (int i = 0; i < diceCombinations.length; i++) {
                    if (jatsi.players.get(jatsi.player).getScores().getScore(diceCombinations[i]) == -1) {
                        list.add(diceCombinations[i]);
                    }
                }
                int index = 0;
                int max = 0;
                int[] numbers = new int[5];
                for (int i = 0; i < 5; i++) {
                    numbers[i] = jatsi.dice[i].getValue();
                }
                for (int i = 0; i < list.size(); i++) {
                    if (Calculator.count(numbers, list.get(i)) > max) {
                        index = i;
                        max = Calculator.count(numbers, list.get(i));
                    }
                }
                Object[] combinations = list.toArray();
                String combination = null;
                while (combination == null) {
                    combination = (String)javax.swing.JOptionPane.showInputDialog(null, "Which combination do you want to use?", "Input", javax.swing.JOptionPane.INFORMATION_MESSAGE, null, combinations, combinations[index]);
                }
                int score = jatsi.putScore(combination, jatsi.players.get(jatsi.player));
                Scorecard.setValueAt(score, combinationToInteger(combination), jatsi.player+1);
            } else {
                int score = jatsi.putScore(diceCombinations[jatsi.counter], jatsi.players.get(jatsi.player));
                Scorecard.setValueAt(score, pakkocounter, jatsi.player+1);
                pakkocounter++;
                if (pakkocounter == 6) {
                    pakkocounter = 8;
                }
            }
            if (jatsi.dice[0].isLocked()) {
                dieButton1.setSelected(false);
            }
            if (jatsi.dice[1].isLocked()) {
                dieButton2.setSelected(false);
            }
            if (jatsi.dice[2].isLocked()) {
                dieButton3.setSelected(false);
            }
            if (jatsi.dice[3].isLocked()) {
                dieButton4.setSelected(false);
            }
            if (jatsi.dice[4].isLocked()) {
                dieButton5.setSelected(false);
            }
            if (!(jatsi.counter == 14 && jatsi.player == jatsi.players.size()-1)) {
                jatsi.freeDice();
                jatsi.nextPlayer();
                rollButton.setEnabled(true);
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Game over!");
                int winner = 0;
                int winningScore = 0;
                for (int i = 0; i < jatsi.players.size(); i++) {
                    jatsi.players.get(i).getScores().setUpperTotal();
                    jatsi.players.get(i).getScores().setTotal();
                    if (winningScore < jatsi.players.get(i).getScores().getScore("total")) {
                        winner = i;
                        winningScore = jatsi.players.get(i).getScores().getScore("total");
                    }
                    Scorecard.setValueAt(jatsi.players.get(i).getScores().getScore("upper total"), 6, i+1);
                    Scorecard.setValueAt(jatsi.players.get(i).getScores().getScore("bonus"), 7, i+1);
                    Scorecard.setValueAt(jatsi.players.get(i).getScores().getScore("total"), 17, i+1);
                    highscores.addScore(jatsi.players.get(i).getName(), jatsi.players.get(i).getScores().getScore("total"));
                }
                javax.swing.JOptionPane.showMessageDialog(null, jatsi.players.get(winner).getName() + " won with " + winningScore + " points!");
            }
        }
    }//GEN-LAST:event_rollButtonActionPerformed

    private void dieButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieButton1ActionPerformed
        if (jatsi.turn != 0) {
            jatsi.dice[0].toggle();
        } else {
            dieButton1.setSelected(false);
        }
    }//GEN-LAST:event_dieButton1ActionPerformed

    private void dieButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieButton2ActionPerformed
        if (jatsi.turn != 0) {
            jatsi.dice[1].toggle();
        } else {
            dieButton2.setSelected(false);
        }
    }//GEN-LAST:event_dieButton2ActionPerformed

    private void dieButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieButton3ActionPerformed
        if (jatsi.turn != 0) {
            jatsi.dice[2].toggle();
        } else {
            dieButton3.setSelected(false);
        }
    }//GEN-LAST:event_dieButton3ActionPerformed

    private void dieButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieButton4ActionPerformed
        if (jatsi.turn != 0) {
            jatsi.dice[3].toggle();
        } else {
            dieButton4.setSelected(false);
        }
    }//GEN-LAST:event_dieButton4ActionPerformed

    private void dieButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieButton5ActionPerformed
        if (jatsi.turn != 0) {
            jatsi.dice[4].toggle();
        } else {
            dieButton5.setSelected(false);
        }
    }//GEN-LAST:event_dieButton5ActionPerformed
    
    private void highScoresMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScoresMenuItemActionPerformed
        javax.swing.JOptionPane.showMessageDialog(null, highscores);
    }//GEN-LAST:event_highScoresMenuItemActionPerformed

    private void newGameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameMenuItemActionPerformed
        this.jatsi = new Game();
        String[] values = {"1", "2", "3", "4", "5", "6"};
        String number = (String)javax.swing.JOptionPane.showInputDialog(null, "How many players wish to play?", "Input", javax.swing.JOptionPane.INFORMATION_MESSAGE, null, values, values[0]);
        if (number == null) {
            return;
        }
        int numberOfPlayers = Integer.parseInt(number);
        String name = "";
        for (int i = 0; i < numberOfPlayers; i++) {
            while (name.equals("")) {
                name = javax.swing.JOptionPane.showInputDialog("Player " + (i+1) + ", please enter your name.");
                if (name == null) {
                    return;
                }
            }
            jatsi.addPlayer(name);
            Scorecard.getColumnModel().getColumn(i+1).setHeaderValue(name);
            name = "";
        }
        for (int i = 0; i < 18; i++) {
            for (int j = 1; j < 7; j++) {
                Scorecard.setValueAt("", i, j);
            }
        }
        String[] choices = {"Perusjatsi", "Pakkojatsi"};
        int response = javax.swing.JOptionPane.showOptionDialog(null, "Please choose game mode.", "Input", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE, null, choices, "Perusjatsi");
        if (response == 0) {
            pakkojatsi = false;
        } else {
            pakkojatsi = true;
        }
        pakkocounter = 0;
        rollButton.setEnabled(true);
    }//GEN-LAST:event_newGameMenuItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JTable Scorecard;
    private javax.swing.JToggleButton dieButton1;
    private javax.swing.JToggleButton dieButton2;
    private javax.swing.JToggleButton dieButton3;
    private javax.swing.JToggleButton dieButton4;
    private javax.swing.JToggleButton dieButton5;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem highScoresMenuItem;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newGameMenuItem;
    private javax.swing.JButton rollButton;
    // End of variables declaration//GEN-END:variables
}
